/* ui 原型库统一出口(barrel):页面/模板只从此入口引入;组件契约见 docs/DESIGN-CONTRACT.md §3.3 与 UI-TEMPLATES.md */
export { default as CardShell } from './CardShell'
export { default as CardState } from './CardState'
export { default as DataTable } from './DataTable'
export { default as DatasetSelector } from './DatasetSelector'
export { default as EmptyState } from './EmptyState'
export { default as FormulaText } from './FormulaText'
export { default as FormRow } from './FormRow'
export { default as HScroll } from './HScroll'
export { default as IconTextButton } from './IconTextButton'
export { default as InfiniteScrollSentinel } from './InfiniteScrollSentinel'
export { default as InfiniteScrollToggle, useInfiniteScrollEnabled } from './InfiniteScrollToggle'
export { default as MetricStat } from './MetricStat'
export { default as PageHeader } from './PageHeader'
export { default as PageShell } from './PageShell'
export { default as PageState } from './PageState'
export { default as ResearchSplit, RESEARCH_SPLIT_STACK_AT } from './ResearchSplit'
export { default as SignalTag } from './SignalTag'
export { default as SkeletonBlock } from './SkeletonBlock'
export { default as SegmentToolbar } from './SegmentToolbar'
export { default as StatStrip } from './StatStrip'
export { default as StatusTag, JOB_STATUS_META, SIGNAL_STATUS_META, PUBLISH_STATUS_META } from './StatusTag'
export { default as TaskProgress } from './TaskProgress'
export { default as Toolbar } from './Toolbar'
export { default as TriStateGroup } from './TriStateGroup'

export type { DataTableProps } from './DataTable'
export type { DatasetOption } from './DatasetSelector'
export type { InfiniteScrollToggleProps } from './InfiniteScrollToggle'
export type { InfiniteScrollSentinelProps } from './InfiniteScrollSentinel'
export type { SegmentOption } from './SegmentToolbar'
export type { StatStripItem } from './StatStrip'
export type { TaskJob } from './TaskProgress'
export type { TriStateOption } from './TriStateGroup'
