"""信号元数据单一事实源：code → (中文名, 分类, 一句话说明, 默认参数) 与常用度排序。

由 lib/signals/engine.py 的注册表（SIGNAL_TYPES）派生，API（app/api/signals.py）、
copilot（core/copilot/commands.py）、paper（core/paper/）共享。
新增信号时必须同步本目录，否则 /catalog 接口与 copilot 信号解析会缺条目。
分类限：趋势|动量|反转|波动|量能|形态|位置
"""

from __future__ import annotations

# 信号目录元数据：code → (中文名, 分类, 一句话说明, 默认参数)
SIGNAL_CATALOG: dict[str, tuple[str, str, str, dict]] = {
    "trend_breakout": (
        "趋势突破",
        "趋势",
        "收盘突破 N 日高点（超出 min_pct%）",
        {"window": 20, "min_pct": 0.5},
    ),
    "price_up": ("当日上涨", "动量", "当日涨幅 ≥ min_pct%", {"min_pct": 3.0}),
    "volume_surge": (
        "放量",
        "量能",
        "量比 ≥ ratio（现量/前 window 日均量）",
        {"ratio": 2.0, "window": 5},
    ),
    "rsi_cross_up": (
        "RSI 上穿",
        "反转",
        "RSI(window) 上穿 threshold（超卖反转）",
        {"threshold": 30, "window": 14},
    ),
    "rsi_above": (
        "RSI 超买",
        "反转",
        "RSI(window) > threshold（超买警示）",
        {"threshold": 70, "window": 14},
    ),
    "macd_golden_cross": ("MACD 金叉", "动量", "DIF 上穿 DEA（金叉）", {}),
    "boll_breakout": ("布林突破", "波动", "收盘突破布林上轨", {}),
    "kdj_golden_cross": ("KDJ 金叉", "反转", "K 上穿 D（金叉）", {}),
    "ma_support": ("MA 支撑", "位置", "收盘贴近 MA(window)（±1%）", {"window": 20}),
    "consecutive_up": (
        "连阳上攻",
        "动量",
        "连续 days 日收涨，累计涨幅 ≥ min_pct%",
        {"days": 3, "min_pct": 0.0},
    ),
    "ma_bullish": (
        "均线多头",
        "趋势",
        "MA5 > MA10 > MA20 多头排列",
        {"short": 5, "mid": 10, "long": 20},
    ),
    "volume_shrink": (
        "缩量回调",
        "量能",
        "量比 < max_ratio 且当日跌幅 ≥ min_drop_pct%",
        {"max_ratio": 0.6, "min_drop_pct": 1.0},
    ),
    "ma_golden_cross": (
        "均线金叉",
        "趋势",
        "MA(short) 上穿 MA(long)（金叉）",
        {"short": 5, "long": 10},
    ),
    "macd_dead_cross": ("MACD 死叉", "动量", "DIF 下穿 DEA（死叉，警示）", {}),
    "kdj_oversold": ("KDJ 超卖", "反转", "K 值 < threshold（超卖）", {"threshold": 20}),
    "kdj_overbought": (
        "KDJ 超买",
        "反转",
        "K 值 > threshold（超买）",
        {"threshold": 80},
    ),
    "rsi_oversold": (
        "RSI 超卖",
        "反转",
        "RSI(window) < threshold（超卖）",
        {"threshold": 30, "window": 14},
    ),
    "breakout_new_high": ("60日新高", "动量", "收盘创 window 日新高", {"window": 60}),
    "break_new_low": ("创N日新低", "动量", "收盘创 window 日新低", {"window": 60}),
    "limit_up": ("涨停", "动量", "当日涨停（主板 ≥9.9%，创业/科创 ≥19.9%）", {}),
    "limit_down": ("跌停", "动量", "当日跌停（主板 ≤-9.9%，创业/科创 ≤-19.9%）", {}),
    "big_bullish": (
        "大阳线",
        "动量",
        "大阳线：涨幅 ≥ min_pct% 且收阳",
        {"min_pct": 5.0},
    ),
    "big_bearish": ("大阴线", "动量", "大阴线：当日跌幅 ≥ min_pct%", {"min_pct": 5.0}),
    "long_upper_shadow": ("长上影", "形态", "上影线 > 2×实体 且 > 下影线", {}),
    "hammer": ("锤子线", "形态", "长下影 > 2×实体 且收盘在区间上半部", {}),
    "volume_price_surge": (
        "放量长阳",
        "量能",
        "量比 ≥ ratio 且涨幅 ≥ min_pct%",
        {"ratio": 2.0, "min_pct": 3.0},
    ),
    "ma_squeeze": (
        "均线粘合",
        "波动",
        "MA5/10/20 极差 < max_pct%（粘合）",
        {"max_pct": 1.0},
    ),
    "above_ma20": ("站上20日线", "位置", "收盘 > MA(window)", {"window": 20}),
    "below_ma20": ("跌破20日线", "位置", "收盘 < MA(window)", {"window": 20}),
    "turnover_spike": (
        "换手激增",
        "量能",
        "换手率 > mult× 前5日均值（需 turnover_rate 列）",
        {"mult": 2.0},
    ),
    "volume_divergence": (
        "量价背离",
        "量能",
        "创 window 日新高但量能未同步放大",
        {"window": 20, "vol_window": 5},
    ),
    "consecutive_limit_up": ("连续涨停", "动量", "近 days 日连续涨停", {"days": 2}),
    "doji": (
        "十字星",
        "形态",
        "|收盘-开盘|/开盘 < max_body_pct% 且带上下影",
        {"max_body_pct": 0.5},
    ),
    "macd_hist_up": ("MACD柱放大", "动量", "MACD 红柱连续 days 日放大", {"days": 2}),
    "volume_breakout_high": (
        "放量突破前高",
        "量能",
        "量比 ≥ ratio 且收盘突破 window 日高点",
        {"ratio": 2.0, "window": 20},
    ),
    "price_gap_up": ("跳空高开", "动量", "开盘较昨收高开 ≥ min_pct%", {"min_pct": 1.0}),
    "gap_down": ("跳空低开", "动量", "开盘较昨收低开 ≥ min_pct%", {"min_pct": 1.0}),
    "price_cross_up_ma": (
        "上穿均线",
        "趋势",
        "收盘上穿 MA(window)（昨在下今在上）",
        {"window": 20},
    ),
    "price_cross_down_ma": (
        "跌破均线",
        "趋势",
        "收盘跌破 MA(window)（昨在上今在下）",
        {"window": 20},
    ),
    "ma20_cross_ma60": (
        "MA20上穿MA60",
        "趋势",
        "MA(short) 上穿 MA(long)（中期趋势转多）",
        {"short": 20, "long": 60},
    ),
    "ema_golden_cross": (
        "EMA金叉",
        "趋势",
        "EMA(short) 上穿 EMA(long)",
        {"short": 12, "long": 26},
    ),
    "macd_hist_shrink": (
        "MACD红柱缩小",
        "动量",
        "MACD 红柱连续 days 日缩小（动能衰减）",
        {"days": 2},
    ),
    "kdj_dead_cross": ("KDJ死叉", "反转", "K 下穿 D（死叉，警示）", {}),
    "rsi_cross_down": (
        "RSI下穿",
        "反转",
        "RSI(window) 下穿 threshold（超买回落）",
        {"threshold": 70, "window": 14},
    ),
    "mtm_cross_up": (
        "MTM转正",
        "动量",
        "MTM(window) 上穿 0（动量转正）",
        {"window": 12},
    ),
    "roc_cross_up": (
        "ROC转正",
        "动量",
        "ROC(window) 上穿 0（变动率转正）",
        {"window": 12},
    ),
    "cci_cross_up": (
        "CCI突破100",
        "动量",
        "CCI(window) 上穿 +100（强势启动）",
        {"window": 14},
    ),
    "cci_cross_down": (
        "CCI破位-100",
        "动量",
        "CCI(window) 下穿 -100（弱势破位）",
        {"window": 14},
    ),
    "trix_golden_cross": ("TRIX金叉", "动量", "TRIX 上穿 MATRIX（长线动能转多）", {}),
    "dmi_bullish": ("DMI多头", "趋势", "PDI > MDI 且 ADX 走强", {}),
    "wr_oversold": ("WR超卖", "反转", "WR(window) > 80（超卖）", {"window": 10}),
    "wr_overbought": ("WR超买", "反转", "WR(window) < 20（超买）", {"window": 10}),
    "cci_oversold": ("CCI超卖", "反转", "CCI(window) < -100（超卖）", {"window": 14}),
    "cci_overbought": ("CCI超买", "反转", "CCI(window) > +100（超买）", {"window": 14}),
    "bias_overbought": (
        "BIAS超买",
        "反转",
        "BIAS(window) > 20%（正乖离过大）",
        {"window": 24},
    ),
    "bias_oversold": (
        "BIAS超卖",
        "反转",
        "BIAS(window) < -20%（负乖离过大）",
        {"window": 24},
    ),
    "psy_above": ("PSY超买", "反转", "PSY(window) > 75（心理线超买）", {"window": 12}),
    "psy_below": ("PSY超卖", "反转", "PSY(window) < 25（心理线超卖）", {"window": 12}),
    "obv_new_high": (
        "OBV新高",
        "量能",
        "OBV 创 window 日新高（量能趋势突破）",
        {"window": 20},
    ),
    "vr_high": ("VR放量区", "量能", "VR(window) > 160（放量区）", {"window": 26}),
    "vr_low": ("VR地量区", "量能", "VR(window) < 40（地量区）", {"window": 26}),
    "atr_expansion": (
        "ATR放大",
        "波动",
        "ATR 较前日放大 ratio 倍（波动加剧）",
        {"ratio": 1.3},
    ),
    "boll_squeeze": (
        "布林收口",
        "波动",
        "布林带宽处 window 日低位分位（变盘前兆）",
        {"window": 20},
    ),
    "bullish_engulfing": ("看涨吞没", "形态", "阳线实体完全吞没前日阴线实体", {}),
    "bearish_engulfing": ("看跌吞没", "形态", "阴线实体完全吞没前日阳线实体", {}),
    "shooting_star": (
        "射击之星",
        "形态",
        "长上影 ≥ 2×实体 且上影 > 2×下影（顶部警示）",
        {},
    ),
}

# 常用度排序（0 = 最常用）：供信号选择 UI 按交易习惯排列
SIGNAL_RANK: dict[str, int] = {
    # 第一梯队：涨停/放量/金叉/突破
    "limit_up": 0,
    "volume_surge": 1,
    "ma_golden_cross": 2,
    "macd_golden_cross": 3,
    "price_up": 4,
    "trend_breakout": 5,
    "breakout_new_high": 6,
    "consecutive_up": 7,
    "kdj_golden_cross": 8,
    "rsi_cross_up": 9,
    "boll_breakout": 10,
    "volume_price_surge": 11,
    "ma_bullish": 12,
    "above_ma20": 13,
    "price_gap_up": 14,
    "macd_hist_up": 15,
    "volume_breakout_high": 16,
    "ma_support": 17,
    "consecutive_limit_up": 18,
    "big_bullish": 19,
    "price_cross_up_ma": 20,
    "ma20_cross_ma60": 21,
    "ema_golden_cross": 22,
    "dmi_bullish": 23,
    "mtm_cross_up": 24,
    "roc_cross_up": 25,
    "cci_cross_up": 26,
    "trix_golden_cross": 27,
    "obv_new_high": 28,
    "bullish_engulfing": 29,
    # 第二梯队：超买超卖/反转
    "rsi_oversold": 30,
    "rsi_above": 31,
    "rsi_cross_down": 32,
    "kdj_oversold": 33,
    "kdj_overbought": 34,
    "wr_oversold": 35,
    "wr_overbought": 36,
    "cci_oversold": 37,
    "cci_overbought": 38,
    "bias_oversold": 39,
    "bias_overbought": 40,
    "psy_above": 41,
    "psy_below": 42,
    "hammer": 43,
    "break_new_low": 44,
    "below_ma20": 45,
    "price_cross_down_ma": 46,
    "macd_dead_cross": 47,
    "kdj_dead_cross": 48,
    "macd_hist_shrink": 49,
    "cci_cross_down": 50,
    "bearish_engulfing": 51,
    "shooting_star": 52,
    "long_upper_shadow": 53,
    "doji": 54,
    # 第三梯队：量能/波动细节
    "volume_shrink": 55,
    "volume_divergence": 56,
    "vr_high": 57,
    "vr_low": 58,
    "atr_expansion": 59,
    "boll_squeeze": 60,
    "ma_squeeze": 61,
    "turnover_spike": 62,
    "limit_down": 63,
    "big_bearish": 64,
    "gap_down": 65,
}
